version: '3.4'

services:
  db:
    container_name: node_ts_es6_babel_db
    restart: always
    build:
      context: docker/postgres/
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=nodetses6babel
      - POSTGRES_DB=nodetses6babel
      - POSTGRES_PASSWORD=nodetses6babel
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - nodetses6babelnet

networks:
  nodetses6babelnet:
    driver: "bridge"

volumes:
  data:
    driver: "local"
